steps:

  - name: "docker/compose"
    id: "Rodando docker-compose"
    args: [ 'up', '-d' ]

  - name: 'docker'
    id: 'Rodando docker ps'
    args: [ 'ps' ]

  # - name: "docker"
  #   id: "Rodando Testes"
  #   args: [ 'exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]
