steps:

  - name: "docker/compose"
    id: "Rodando docker-compose"
    args: [ 'up', '-d' ]

  - name: "dockerize"
    id: "Esperando container app"
    args: [ '-wait', 'tcp://app:9000', '-timeout', '20s' ]

  - name: "docker"
    id: "Rodando Testes"
    args: [ 'exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]
